2. Data preprocessing: 
Data preprocessing is a process of preparing the raw data and making it suitable for a machine learning model.
we'll only take feature not target as target is constant.

Data preprocessing is used to remove problems in our dataset (as dataset will be huge and we can check manually). For ex: missing values

->take data in bell shaped region (for proper distribution of data)
Note: we can either take -1 to 1 or, 0 to 1 depending on our choice.

This is kknown as feature scaling.

Feature Scaling:

Feature scaling is the final step of data preprocessing in machine learning. It is a technique to standardize the independent variables of the dataset in a specific range. In feature scaling, we put our variables in the same range and in the same scale so that no any variable dominate the other variable.

In [ ]:
from sklearn.datasets import load_iris
X,y=load_iris(return_X_y=True)
print(X)
print(y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

- We will go for data preprocessing for only X (features) bcz it is containing the data (data to predict)

*Data preprocessing techniques*

These are some common preprocessing techniques.

- We can use any of the techniques for our model. But the best way is to apply all the techniques and see the result of our model.
- Whichever technique gives us best ans. We'll go for that one.
- With time and practice we get to understand which technique should be used(best suited) for our model.

-> our values will vary from -1 to 1 or 0 to 1 (depending on technique which we have used)

these values are calculated using statistical formals.

For ex: for StandardScaler formula is: y = (x – mean) / standard_deviation

1. Data prerpcessing technique - 1
(using StandardScaler)
(this technique is the simplest first and simplest one)

Below we can see that after data preprocessing techinque using standardScaler our values lies in range -1 to 1

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

#for fitting the value of X to convert it in such a way that i'll get the proper distribution
#fitting the data
#and, printing StandardScaler
print(scaler.fit(X)) #fitting X in StandardScaler method to do something, what it is doing is tranformation which is given below i.e. it is only doing scaling
#transforming the data
print(scaler.transform(X))

#we can see that our data lies from -1 to 1 in exponent mentisa form

StandardScaler()
[[-9.00681170e-01  1.01900435e+00 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00 -1.31979479e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.38535265e+00  3.28414053e-01 -1.39706395e+00 -1.31544430e+00]
 [-1.50652052e+00  9.82172869e-02 -1.28338910e+00 -1.31544430e+00]
 [-1.02184904e+00  1.24920112e+00 -1.34022653e+00 -1.31544430e+00]
 [-5.37177559e-01  1.93979142e+00 -1.16971425e+00 -1.05217993e+00]
 [-1.50652052e+00  7.88807586e-01 -1.34022653e+00 -1.18381211e+00]
 [-1.02184904e+00  7.88807586e-01 -1.28338910e+00 -1.31544430e+00]
 [-1.74885626e+00 -3.62176246e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00  9.82172869e-02 -1.28338910e+00 -1.44707648e+00]
 [-5.37177559e-01  1.47939788e+00 -1.28338910e+00 -1.31544430e+00]
 [-1.26418478e+00  7.88807586e-01 -1.22655167e+00 -1.31544430e+00]
 [-1.26418478e+00 -1.31979479e-01 -1.34022653e+00 -1.44707648e+00]
 [-1.87002413e+00 -1.31979479e-01 -1.51073881e+00 -1.44707648e+00]
 [-5.25060772e-02  2.16998818e+00 -1.45390138

2. Data prerpcessing technique - 2
(using MinMaxScaler)

In [12]:
from sklearn.preprocessing import MinMaxScaler
scaler= MinMaxScaler()

#for fitting the value of X to convert it in such a way that i'll get the proper distribution
#fitting the data
#and, printing MinMaxScaler
print(scaler.fit_transform(X)) #fitting X in MinMaxScaler method to do something, what it is doing is tranformation i.e. it is only doing scaling

#we can see that our data lies from 0 to 1

[[0.22222222 0.625      0.06779661 0.04166667]
 [0.16666667 0.41666667 0.06779661 0.04166667]
 [0.11111111 0.5        0.05084746 0.04166667]
 [0.08333333 0.45833333 0.08474576 0.04166667]
 [0.19444444 0.66666667 0.06779661 0.04166667]
 [0.30555556 0.79166667 0.11864407 0.125     ]
 [0.08333333 0.58333333 0.06779661 0.08333333]
 [0.19444444 0.58333333 0.08474576 0.04166667]
 [0.02777778 0.375      0.06779661 0.04166667]
 [0.16666667 0.45833333 0.08474576 0.        ]
 [0.30555556 0.70833333 0.08474576 0.04166667]
 [0.13888889 0.58333333 0.10169492 0.04166667]
 [0.13888889 0.41666667 0.06779661 0.        ]
 [0.         0.41666667 0.01694915 0.        ]
 [0.41666667 0.83333333 0.03389831 0.04166667]
 [0.38888889 1.         0.08474576 0.125     ]
 [0.30555556 0.79166667 0.05084746 0.125     ]
 [0.22222222 0.625      0.06779661 0.08333333]
 [0.38888889 0.75       0.11864407 0.08333333]
 [0.22222222 0.75       0.08474576 0.08333333]
 [0.30555556 0.58333333 0.11864407 0.04166667]
 [0.22222222 

3. Data prerpcessing technique - 3
(using MaxAbsScaler)

In [13]:
from sklearn.preprocessing import MaxAbsScaler
scaler= MaxAbsScaler()

#for fitting the value of X to convert it in such a way that i'll get the proper distribution
#fitting the data
#and, printing MaxAbsScaler
print(scaler.fit_transform(X)) #fitting X in MaxAbsScaler method to do something, what it is doing is tranformation i.e. it is only doing scaling

#we can see that our data lies from 0 to 1

[[0.64556962 0.79545455 0.20289855 0.08      ]
 [0.62025316 0.68181818 0.20289855 0.08      ]
 [0.59493671 0.72727273 0.1884058  0.08      ]
 [0.58227848 0.70454545 0.2173913  0.08      ]
 [0.63291139 0.81818182 0.20289855 0.08      ]
 [0.6835443  0.88636364 0.24637681 0.16      ]
 [0.58227848 0.77272727 0.20289855 0.12      ]
 [0.63291139 0.77272727 0.2173913  0.08      ]
 [0.55696203 0.65909091 0.20289855 0.08      ]
 [0.62025316 0.70454545 0.2173913  0.04      ]
 [0.6835443  0.84090909 0.2173913  0.08      ]
 [0.60759494 0.77272727 0.23188406 0.08      ]
 [0.60759494 0.68181818 0.20289855 0.04      ]
 [0.5443038  0.68181818 0.15942029 0.04      ]
 [0.73417722 0.90909091 0.17391304 0.08      ]
 [0.72151899 1.         0.2173913  0.16      ]
 [0.6835443  0.88636364 0.1884058  0.16      ]
 [0.64556962 0.79545455 0.20289855 0.12      ]
 [0.72151899 0.86363636 0.24637681 0.12      ]
 [0.64556962 0.86363636 0.2173913  0.12      ]
 [0.6835443  0.77272727 0.24637681 0.08      ]
 [0.64556962 

4. Data prerpcessing technique - 4
(using Quantile Transformation)

Note: before going for this technique we should know how to split data

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X,y,test_size=0.30, random_state=0) #0 is seed value, seed value is used to select same random data 
#which we might have used earlier for traing and testing (ex: we have trained our data with 0,1 earlier and tested for 3,4)
#then again if we are tarinig and testing we'll use same 0,1 for training and 3,4 for testing
#we use seed value to not use same data for training which we have used for testing 

#0.30 is the 30% of the data we are using for testing

print(X_train, y_train)
print(X_test, y_test)

[[5.  2.  3.5 1. ]
 [6.5 3.  5.5 1.8]
 [6.7 3.3 5.7 2.5]
 [6.  2.2 5.  1.5]
 [6.7 2.5 5.8 1.8]
 [5.6 2.5 3.9 1.1]
 [7.7 3.  6.1 2.3]
 [6.3 3.3 4.7 1.6]
 [5.5 2.4 3.8 1.1]
 [6.3 2.7 4.9 1.8]
 [6.3 2.8 5.1 1.5]
 [4.9 2.5 4.5 1.7]
 [6.3 2.5 5.  1.9]
 [7.  3.2 4.7 1.4]
 [6.5 3.  5.2 2. ]
 [6.  3.4 4.5 1.6]
 [4.8 3.1 1.6 0.2]
 [5.8 2.7 5.1 1.9]
 [5.6 2.7 4.2 1.3]
 [5.6 2.9 3.6 1.3]
 [5.5 2.5 4.  1.3]
 [6.1 3.  4.6 1.4]
 [7.2 3.2 6.  1.8]
 [5.3 3.7 1.5 0.2]
 [4.3 3.  1.1 0.1]
 [6.4 2.7 5.3 1.9]
 [5.7 3.  4.2 1.2]
 [5.4 3.4 1.7 0.2]
 [5.7 4.4 1.5 0.4]
 [6.9 3.1 4.9 1.5]
 [4.6 3.1 1.5 0.2]
 [5.9 3.  5.1 1.8]
 [5.1 2.5 3.  1.1]
 [4.6 3.4 1.4 0.3]
 [6.2 2.2 4.5 1.5]
 [7.2 3.6 6.1 2.5]
 [5.7 2.9 4.2 1.3]
 [4.8 3.  1.4 0.1]
 [7.1 3.  5.9 2.1]
 [6.9 3.2 5.7 2.3]
 [6.5 3.  5.8 2.2]
 [6.4 2.8 5.6 2.1]
 [5.1 3.8 1.6 0.2]
 [4.8 3.4 1.6 0.2]
 [6.5 3.2 5.1 2. ]
 [6.7 3.3 5.7 2.1]
 [4.5 2.3 1.3 0.3]
 [6.2 3.4 5.4 2.3]
 [4.9 3.  1.4 0.2]
 [5.7 2.5 5.  2. ]
 [6.9 3.1 5.4 2.1]
 [4.4 3.2 1.3 0.2]
 [5.  3.6 1.

In [18]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(105, 4) (105,)
(45, 4) (45,)


In [20]:
from sklearn.preprocessing import QuantileTransformer
Quantile_Transformer=QuantileTransformer()
print(Quantile_Transformer.fit_transform(X_train))
print(Quantile_Transformer.fit_transform(X_test))

[[0.17307692 0.         0.35096154 0.34615385]
 [0.74038462 0.44230769 0.79807692 0.69711538]
 [0.8125     0.74519231 0.85576923 1.        ]
 [0.5625     0.01442308 0.66826923 0.58173077]
 [0.8125     0.12019231 0.87980769 0.69711538]
 [0.39903846 0.12019231 0.39903846 0.37980769]
 [0.97596154 0.44230769 0.94230769 0.93269231]
 [0.64903846 0.74519231 0.59134615 0.62019231]
 [0.35576923 0.06730769 0.38461538 0.37980769]
 [0.64903846 0.21153846 0.62980769 0.69711538]
 [0.64903846 0.27403846 0.71153846 0.58173077]
 [0.125      0.12019231 0.54326923 0.64903846]
 [0.64903846 0.12019231 0.66826923 0.75961538]
 [0.89423077 0.67307692 0.59134615 0.54326923]
 [0.74038462 0.44230769 0.74519231 0.80769231]
 [0.5625     0.81730769 0.54326923 0.62019231]
 [0.08653846 0.58173077 0.26442308 0.13461538]
 [0.50961538 0.21153846 0.71153846 0.75961538]
 [0.39903846 0.21153846 0.47115385 0.46634615]
 [0.39903846 0.32692308 0.36538462 0.46634615]
 [0.35576923 0.12019231 0.41346154 0.46634615]
 [0.58653846 

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_data.py:2593: UserWarning: n_quantiles (1000) is greater than the total number of samples (105). n_quantiles is set to n_samples.
  "n_samples." % (self.n_quantiles, n_samples)
/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_data.py:2593: UserWarning: n_quantiles (1000) is greater than the total number of samples (45). n_quantiles is set to n_samples.
  "n_samples." % (self.n_quantiles, n_samples)


Method for filling missing values

1. Simple imputer

Note:
*   Mean - avg. of all the values
*   Median - middle value of all the data (arranged in ascending or descending order)..when n is odd then (n+1)/2th value, when n is even then (n/2 + (n/2+1))/2th value

->cloumn data is taken for mean or median


In [ ]:
from sklearn.impute import SimpleImputer
import numpy as np
#NaN is Not a number

#taking a small data to understand simple imputer
X=[[1,2,3],[4,np.NaN,5],[6,7,8]]
imp=SimpleImputer(missing_values=np.NaN, strategy='mean') #this means wherever np.NaN is found it'll take mean
#it takes means of a column i.e. 2+7/2=4.5

print(imp.fit_transform(X))

[[1.  2.  3. ]
 [4.  4.5 5. ]
 [6.  7.  8. ]]


In [ ]:
#we can also use median
X=[[1,2,3],[4,np.NaN,5],[6,7,8]]
imp=SimpleImputer(missing_values=np.NaN, strategy='median') #this means wherever np.NaN is found it'll take median
#it takes median of a column i.e. 2+7/2=4.5

print(imp.fit_transform(X))

[[1.  2.  3. ]
 [4.  4.5 5. ]
 [6.  7.  8. ]]


In [ ]:
#we can also use constant
X=[[1,2,3],[4,np.NaN,5],[6,7,8]]
imp=SimpleImputer(missing_values=np.NaN, strategy='constant') #this means wherever np.NaN is found it'll put constant
#whenver NaN will be numeric it'll be replaced by 0

print(imp.fit_transform(X))

2. We can also fill missing values without SimpleImputer. 

*   First we have to convert our data into dataframe (i.e. representing our data in a proper matrix form)
*   



In [ ]:
import pandas as pd
X=[[1,2,3],[4,np.NaN,5],[6,7,8]]
df=pd.DataFrame(X)
df
#as we can see that NaN column is float type. So, keep in mind that numpy represents(or considers) NaN as float

0    1  2
0  1  2.0  3
1  4  NaN  5
2  6  7.0  8

In [ ]:
print(df.fillna(10))


   0     1  2
0  1   2.0  3
1  4  10.0  5
2  6   7.0  8


Steps to follow for data preprocessing:

1. First we'll handle the missing data using imputer
2. Then we'll split the data into training and testing
3. Then we'll do feature scaling