In [ ]:
l = list() #empty list
print (l)

[]


In [ ]:
l = [1,2,3,4] #list of integers
print (l)

[1, 2, 3, 4]


In [ ]:
l = [1,2,3, 4.5, 5.1] #list of numbers
print (l)

[1, 2, 3, 4.5, 5.1]


In [ ]:
l = ["a","b",'c'] #list of characters
print (l)

['a', 'b', 'c']


In [ ]:
l = [1,2,4.5,'abs',True] #mixed list
print (l)

[1, 2, 4.5, 'abs', True]


In [ ]:
l = ["abc","pqr","xyz"] #list of strings
print (l)

['abc', 'pqr', 'xyz']


In [ ]:
l=list('hello')
print(l)

['h', 'e', 'l', 'l', 'o']


In [ ]:
s=('a','b','c','d','e')
l=list(s)
print(l)

['a', 'b', 'c', 'd', 'e']


In [ ]:
l=list(input("Enter a list"))
print(l)

Enter a listDivya Jaiswal
['D', 'i', 'v', 'y', 'a', ' ', 'J', 'a', 'i', 's', 'w', 'a', 'l']


In [ ]:
l=[1,[2,3],[4,5],[6,7,8],['Divya','Anu','Suchi']] #Nested List
print(l)

[1, [2, 3], [4, 5], [6, 7, 8], ['Divya', 'Anu', 'Suchi']]


In [ ]:
len(l) #length of a list

5

In [ ]:
l[3]  #indexing

[6, 7, 8]

In [ ]:
l[2:4] #slicing

[[4, 5], [6, 7, 8]]

In [ ]:
[-1,2,3] > [1,2,0]

False

In [ ]:
[1,2,3] < [8,9,1]

True

In [ ]:
l1=[1,2]
l2=[5,4,3]
l = l1+l2
print(l)

[1, 2, 5, 4, 3]


In [ ]:
print(l*10) #Replicating a list

[1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3]


In [ ]:
l=l*5
seq = l[2:15:3] #L[start:end:step]
print(seq)

[5, 1, 4, 2, 3]


In [ ]:
l=l*4
print(l)
print(l[::3])

[1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 

In [ ]:
l1=[1,2]
l2=[5,4,3]
l = l1+l2
l=l*3
print(l)
l[0:2] = ['one','two']
print(l)

[1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3]
['one', 'two', 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3]


In [ ]:
l.append('new item') #add an element
print(l)

['one', 'two', 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 'new item']


In [ ]:
l[3] = 'updated item' #replace an element
print(l)

['one', 'two', 5, 'updated item', 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 'new item']


In [ ]:
del l[3]  #delete an item
print(l)

['one', 'two', 5, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 'new item']


In [ ]:
del l[1]  #delete an item
print(l)

['one', 5, 'updated item', 3, 1, 2, 5, 4, 3, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 1, 2, 5, 4, 3, 'new item']


In [ ]:
l[5] = "item 1"
l[6] = "item2"
print(l)

['one', 'two', 5, 3, 1, 'item 1', 'item2', 4, 3, 1, 2, 5, 4, 3, 'new item']


In [ ]:
del l[5:7]  #delete a slice
print(l)

['one', 'two', 5, 3, 1, 4, 3, 1, 2, 5, 4, 3, 'new item']


In [ ]:
l.pop() #remove last element of the list
print(l)

['one', 'two', 5, 3, 1, 4, 3, 1, 2, 5, 4, 3]


In [ ]:
l.pop(2) #removes an element at a position
print(l)

['one', 'two', 1, 4, 3, 1, 2, 5, 4, 3]


In [ ]:
l.index(1) #prints an element at position x

2

In [ ]:
t=['a','b','Banasthali',1,2,3]
l.extend(t)
print(l)

['one', 'two', 1, 4, 3, 1, 2, 5, 4, 3, 'a', 'b', 'Banasthali', 1, 2, 3]


In [ ]:
l.insert(4,"Hello")
print(l)

['one', 'two', 1, 4, 'Hello', 3, 1, 2, 5, 4, 3, 'a', 'b', 'Banasthali', 1, 2, 3]


In [ ]:
if 1 not in l:
    print("Element not found")
else:
    l.remove(1)
    print("Element Deleted")
print(l)

Element not found
['one', 'two', 4, 'Hello', 2, 5, 4, 'a', 'b', 'Banasthali', 2]


In [ ]:
l.append(4)
l.count(4)

3

In [ ]:
print(l)
l.reverse()
print(l)

['one', 'two', 4, 'Hello', 2, 5, 4, 'a', 'b', 'Banasthali', 2, 4]
[4, 2, 'Banasthali', 'b', 'a', 4, 5, 2, 'Hello', 4, 'two', 'one']


In [ ]:
l1=[]'e','i','q','a','q','p','b']
l2=l1
l1.sort()
print(l1)
print(sorted(l2))

('e', 'i', 'q', 'a', 'q', 'p', 'b')
['a', 'b', 'e', 'i', 'p', 'q', 'q']


TypeError: 'tuple' object does not support item assignment

In [ ]:
l.clear()
print(l)

[]


# Creating a Matrix

In [ ]:
R = int(input("Enter the number of rows:")) 
C = int(input("Enter the number of columns:")) 
  
# Initialize matrix 
matrix = [] 
print("Enter the entries rowwise:") 
  
# For user input 
for i in range(R):          # A for loop for row entries 
    a =[] 
    for j in range(C):      # A for loop for column entries 
         a.append(int(input())) 
    matrix.append(a) 
  
# For printing the matrix 
for i in range(R): 
    for j in range(C): 
        print(matrix[i][j], end = " ") 
    print() 

Enter the number of rows:2
Enter the number of columns:2
Enter the entries rowwise:
1
2
3
4
1 2 
3 4 


# Lab 4
1. WAP to find minimum element from a list of integers alongwith its index in the list
2. WAP to calcualte mean of a given list of numbers
3. WAP to search an element in a list
4. WAP to count the frequency of an element in a list
5. WAP to find frequencies of all elements in a list
6. WAP to extact two slices from a list and add the slices and find which one is greater
7. WAP to find second largest number of a list
8. WAP to input a list of numbers and shift all zeros to the right and all non zeros to left of the list
9. WAP to add two matrices
10. WAP to multiply two matrices
11. WAP to print transpose of a matrix
12. WAP to add elements of diagonal of a matrix
13. WAP to find an element in a matrix
14. WAP to find inverse of a matrix

WAP to find minimum element from a list of integers alongwith its index in the list

In [1]:
l=[15,6,9,1,0,8]
min=1000
for i in l:
    if i < min:
        min=i
idx=l.index(min)
print("Minimum Element is {}".format(min) , end = "\t")
print("Index is {}".format(idx))

Minimum Element is 0	Index is 4


WAP to calcualte mean of a given list of numbers

In [2]:
l=[10,9,8,7,6,5,4]
length= len(l)
mean=sum=0;
for i in range(0,length):
  sum=sum+l[i]
mean=sum/length
print("The mean of the given list is ",mean)

The mean of the given list is  7.0


WAP to search an element in a list

In [5]:
l=[10,9,8,7,4,5,6,2]
length=len(l)
element=int(input("Enter element to search"))
for i in range(0,length):
  if element == l[i]:
    print("Element is present")
    break
else:
    print("Element not present")


Enter element to search11
Element not present


WAP to find frequencies of all elements in a list

In [11]:
lst = eval(input("Enter a list :-"))
for i in lst :
    feq = lst.count(i)
    print("Frequency of ",i,"=",feq)

Enter a list :-5,5,5,3,5,2,1,2,1,2,4,4,7
Frequency of  5 = 4
Frequency of  5 = 4
Frequency of  5 = 4
Frequency of  3 = 1
Frequency of  5 = 4
Frequency of  2 = 3
Frequency of  1 = 2
Frequency of  2 = 3
Frequency of  1 = 2
Frequency of  2 = 3
Frequency of  4 = 2
Frequency of  4 = 2
Frequency of  7 = 1


WAP to count the frequency of an element in a list

In [12]:
import collections
my_list = [10,10,10,10,20,20,20,20,40,40,50,50,30]
print("Original List : ",my_list)
ctr = collections.Counter(my_list)
print("Frequency of the elements in the List : ",ctr)

Original List :  [10, 10, 10, 10, 20, 20, 20, 20, 40, 40, 50, 50, 30]
Frequency of the elements in the List :  Counter({10: 4, 20: 4, 40: 2, 50: 2, 30: 1})


WAP to extact two slices from a list and add the slices and find which one is greater

In [13]:
List = [1, 2, 3, 4, 5, 6, 7, 8, 9]
 
print("\nOriginal List:\n", List)
 
print("\nSliced Lists: ")
 
print(List[3:9:2])
 
print(List[::2])
 
print(List[::])


Original List:
 [1, 2, 3, 4, 5, 6, 7, 8, 9]

Sliced Lists: 
[4, 6, 8]
[1, 3, 5, 7, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


WAP to find second largest number of a list

In [14]:
list1 = [10, 20, 4, 45, 99]
 
# sorting the list
list1.sort()
 
print("Second largest element is:", list1[-2])

Second largest element is: 45


WAP to input a list of numbers and shift all zeros to the right and all non zeros to left of the list

In [17]:
a = [1, 2, 0, 0, 0, 3, 6]
temp = []
zero = []

for i in range(len(a)):
    if a[i] !=0:
        temp.append(a[i])
    else:
        zero.append(a[i])

print(temp+zero)

[1, 2, 3, 6, 0, 0, 0]


WAP to add two matrices

In [18]:
A = [[12,7,3],

    [4 ,5,6],

    [7 ,8,9]]

B = [[5,8,1],

    [6,7,3],

    [4,5,9]]

result = [[0,0,0],

         [0,0,0],

         [0,0,0]]


for x in range(len(A)):


   for y in range(len(A[0])):

       result[x][y] = A[x][y] + B[x][y]

for q in result:

   print(q)

[17, 15, 4]
[10, 12, 9]
[11, 13, 18]


WAP to multiply two matrices

In [19]:
# Program to multiply two matrices using nested loops

X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]

result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]

for i in range(len(X)):
   
   for j in range(len(Y[0])):
      
       for k in range(len(Y)):
           result[i][j] += X[i][k] * Y[k][j]

for r in result:
   print(r)

[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


WAP to print transpose of a matrix

In [21]:
X = [[12,7],
    [4 ,3],
    [3 ,9]]

result = [[0,0,0],
         [0,0,0]]
for i in range(len(X)):
   
   for j in range(len(X[0])):
       result[j][i] = X[i][j]

for r in result:
   print(r)

[12, 4, 3]
[7, 3, 9]


WAP to add elements of diagonal of a matrix

In [23]:
mtrxrows = int(input('Enter some random number of rows of the matrix = '))
mtrxcols = int(input('Enter some random number of columns of the matrix = '))

mtrx = []

for n in range(mtrxrows):
   
    l = list(map(int, input(
        'Enter {'+str(mtrxcols)+'} elements of row {'+str(n+1)+'} separated by spaces = ').split()))
    
    mtrx.append(l)

diagnl_sum = 0
for n in range(mtrxrows):
      
    for m in range(mtrxcols):
      
        if n == m:
         
            diagnl_sum += mtrx[n][m]

print("The Sum of all Diagonal elements of a given Matix = ", diagnl_sum)Matrix=[[0]*M]*M
sum=0
for i in range(M):
    for j in range(M):
        if i==j:
            sum=sum+Matrix[i][j]
        elif i+j=M-1:
            sum=sum+Matrix[i][j]
print(sum)

SyntaxError: ignored

WAP to find inverse of a matrix

In [24]:
import numpy as np
  
# Taking a 4 * 4 matrix
A = np.array([[6, 1, 1, 3],
              [4, -2, 5, 1],
              [2, 8, 7, 6],
              [3, 1, 9, 7]])
  
# Calculating the inverse of the matrix
print(np.linalg.inv(A))

[[ 0.13368984  0.10695187  0.02139037 -0.09090909]
 [-0.00229183  0.02673797  0.14820474 -0.12987013]
 [-0.12987013  0.18181818  0.06493506 -0.02597403]
 [ 0.11000764 -0.28342246 -0.11382735  0.23376623]]
