In [1]:
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
A.diagonal().sum()

15

In [3]:
B = np.matrix('[1,2,3;4,5,6;6,7,8]')
B

matrix([[1, 2, 3],
        [4, 5, 6],
        [6, 7, 8]])

In [4]:
B.diagonal()

matrix([[1, 5, 8]])

In [5]:
lst =B.tolist()
lst

[[1, 2, 3], [4, 5, 6], [6, 7, 8]]

In [6]:
lst =A.tolist()
lst

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
lst=[1,2,3,4,5,6]

In [8]:
print(lst)

[1, 2, 3, 4, 5, 6]


In [9]:
A=np.array(lst)

In [10]:
A

array([1, 2, 3, 4, 5, 6])

In [11]:
type(A)

numpy.ndarray

In [12]:
lst=[[1,2,3],[4,5,6]]
lst

[[1, 2, 3], [4, 5, 6]]

In [13]:
B=np.matrix(lst)
B

matrix([[1, 2, 3],
        [4, 5, 6]])

## Lab 9
1. WAP to create a numpy array and find indices of non-zero elements
2. WAP to create a numpy to create a 3x3 identity matrix 
3. WAP to create a numpy to create a 3x3x3 array with random values
4. WAP to create a numpy to create a random vector of size 30 and find the mean value
5. WAP to create a numpy to multiply a 5x3 matrix by a 3x2 matrix 
6. WAP to create a numpy to input two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))
7. WAP to print all the values of an array

In [15]:
# 1.WAP to create a numpy array and find indices of non-zero elements
import numpy as np
arr = np.array([[0, 8, 0], [7, 0, 0], [-5, 0, 1]])
  
print ("Input  array : \n", arr)
    
out_tpl = np.nonzero(arr)
print ("Indices of non zero elements : ", out_tpl) 

Input  array : 
 [[ 0  8  0]
 [ 7  0  0]
 [-5  0  1]]
Indices of non zero elements :  (array([0, 1, 2, 2]), array([1, 0, 0, 2]))


In [16]:
# 2. WAP to create a numpy to create a 3x3 identity matrix
import numpy as np
array_2D=np.identity(3)
print('3x3 matrix:')
print(array_2D)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
# 3. WAP to create a numpy to create a 3x3x3 array with random values
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.90370547 0.32353988 0.14426377]
  [0.3571718  0.69236907 0.24438042]
  [0.23093137 0.04642683 0.78736321]]

 [[0.17260673 0.35070824 0.95846759]
  [0.6313828  0.31899042 0.4776999 ]
  [0.95166453 0.54618415 0.24175226]]

 [[0.40275017 0.21736545 0.20687576]
  [0.45544732 0.08017275 0.02065706]
  [0.79042602 0.60480393 0.60758256]]]


In [18]:
# 4. WAP to create a numpy to create a random vector of size 30 and find the mean value
import numpy as np
Z = np.random.random(30)
print(Z)
m = Z.mean()
print ("Mean value of following vector : ",m)

[0.16274711 0.03441541 0.83786973 0.04135378 0.31053942 0.51691552
 0.60186862 0.48474297 0.44905941 0.16983743 0.32345737 0.67967052
 0.66116652 0.95541276 0.22672262 0.60036902 0.07988323 0.5691331
 0.99477931 0.15976884 0.81979079 0.53714716 0.48778659 0.23885034
 0.10248946 0.85699339 0.88409614 0.32100132 0.50204986 0.00467057]
Mean value of following vector :  0.4538196104442983


In [19]:
# 5. WAP to create a numpy to multiply a 5x3 matrix by a 3x2 matrix
import numpy as np
x = np.random.random((5,3))
print("First array:")
print(x)
y = np.random.random((3,2))
print("Second array:")
print(y)
z = np.dot(x, y)
print("Dot product of two arrays:")
print(z)

First array:
[[0.64730338 0.19358759 0.50638969]
 [0.72178618 0.8887926  0.19272136]
 [0.44517246 0.2923738  0.34655628]
 [0.79435258 0.63228592 0.31131005]
 [0.58532161 0.77422913 0.60604422]]
Second array:
[[0.12615297 0.61796031]
 [0.90750535 0.6994317 ]
 [0.06412281 0.84250389]]
Dot product of two arrays:
[[0.28981214 0.96204438]
 [0.90999734 1.23005342]
 [0.34371277 0.77156942]
 [0.69397486 1.19539911]
 [0.81531838 1.41382053]]


In [20]:
# 6. WAP to create a numpy to input two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))
import numpy as np
x = np.array([1,2,3,4])
y = np.array([5,6,7])
c= 1.0 / (x.reshape((-1,1)) - y)
print(c)

[[-0.25       -0.2        -0.16666667]
 [-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


In [21]:
# 7. WAP to print all the values of an array
import numpy as np
import sys
nums = np.arange(20)
np.set_printoptions(threshold=sys.maxsize)
print(nums)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
