#**28-02-22**

At the end we have to calculate the accuracy in terms of mean square error etc. bcz it is a regression model.

In [1]:
from google.colab import files
uploaded= files.upload()

Saving insurance.csv to insurance.csv


In [2]:
import pandas as pd #for data manipulation
import numpy as np #for data manipulation

In [4]:
import io
df=pd.read_csv(io.BytesIO(uploaded['insurance.csv'])) 
#dataset is now stored in a pandas Dataframe

In [6]:
print('\nNumber of rows and columns in the dataset : ',df.shape)
print('')

#looking into top few rows and columns of the dataset
df.head()


Number of rows and columns in the dataset :  (1338, 7)



age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [7]:
df.describe()

age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [8]:
df.isnull()

age    sex    bmi  children  smoker  region  charges
0     False  False  False     False   False   False    False
1     False  False  False     False   False   False    False
2     False  False  False     False   False   False    False
3     False  False  False     False   False   False    False
4     False  False  False     False   False   False    False
...     ...    ...    ...       ...     ...     ...      ...
1333  False  False  False     False   False   False    False
1334  False  False  False     False   False   False    False
1335  False  False  False     False   False   False    False
1336  False  False  False     False   False   False    False
1337  False  False  False     False   False   False    False

[1338 rows x 7 columns]

In [10]:
#count total NaN at each column in a DataFrame
print('\n Count total NaN at eacch column in a DataFrame :\n\n',
      df.isnull().sum())


 Count total NaN at eacch column in a DataFrame :

 age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64


In [12]:
#dummy variable
categorical_columns= ['sex', 'children', 'smoker', 'region']
df_encode= pd.get_dummies(data=df, prefix='OHE', prefix_sep='_',
                          columns=categorical_columns,
                          drop_first=True,
                          dtype='int8')

In [14]:
#lets verify the dummy variable process

print('columns in original dataframe : \n', df.columns.values)
print('\nNumber of rows and columns in the dataset : ',df.shape)
print('Columns in dataframe after encoding dummy varibale: \n',df_encode.columns.values)
df_encode.head()

columns in original dataframe : 
 ['age' 'sex' 'bmi' 'children' 'smoker' 'region' 'charges']

Number of rows and columns in the dataset :  (1338, 7)
Columns in dataframe after encoding dummy varibale: 
 ['age' 'bmi' 'charges' 'OHE_male' 'OHE_1' 'OHE_2' 'OHE_3' 'OHE_4' 'OHE_5'
 'OHE_yes' 'OHE_northwest' 'OHE_southeast' 'OHE_southwest']


age     bmi      charges  OHE_male  OHE_1  OHE_2  OHE_3  OHE_4  OHE_5  \
0   19  27.900  16884.92400         0      0      0      0      0      0   
1   18  33.770   1725.55230         1      1      0      0      0      0   
2   28  33.000   4449.46200         1      0      0      1      0      0   
3   33  22.705  21984.47061         1      0      0      0      0      0   
4   32  28.880   3866.85520         1      0      0      0      0      0   

   OHE_yes  OHE_northwest  OHE_southeast  OHE_southwest  
0        1              0              0              1  
1        0              0              1              0  
2        0              0              1              0  
3        0              1              0              0  
4        0              1              0              0

In [15]:
##log transform
df_encode['charges']= np.log(df_encode['charges'])

In [17]:
X=df_encode.drop(['charges'],axis=1)
y=df_encode['charges']

print(X.shape, y.shape)

(1338, 12) (1338,)


In [22]:
from sklearn import preprocessing

scaler=preprocessing.StandardScaler().fit(X)
scaler

StandardScaler()

In [23]:
x_scaled= scaler.transform(X)

In [24]:
scaler.mean_

array([3.92070254e+01, 3.06633969e+01, 5.05231689e-01, 2.42152466e-01,
       1.79372197e-01, 1.17339312e-01, 1.86846039e-02, 1.34529148e-02,
       2.04783259e-01, 2.42899851e-01, 2.72047833e-01, 2.42899851e-01])

In [25]:
scaler.scale_

array([14.04470904,  6.09590764,  0.49997263,  0.4283861 ,  0.38366367,
        0.32182417,  0.1354086 ,  0.11520388,  0.40354315,  0.42883507,
        0.44501439,  0.42883507])

In [27]:
x_scaled.mean(axis=0)

array([-1.80556450e-16, -2.12419353e-16, -1.23468749e-16, -1.85866934e-17,
        8.89506041e-17, -4.24838706e-17, -4.11562496e-17, -1.19485886e-17,
        1.06209676e-17,  1.06209676e-16, -1.06209676e-17,  1.03554435e-16])

In [28]:
x_scaled.std(axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

-> splitting the data :

In [30]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.20, random_state=7)

In [31]:
from sklearn import svm

In [32]:
model_svr= svm.SVR()

In [33]:
model_svr.fit(X_train, y_train)

SVR()

In [34]:
y_pred=model_svr.predict(X_test)

In [37]:
import numpy as np
from sklearn.metrics import mean_absolute_error

from sklearn import metrics

In [38]:
print(metrics.mean_absolute_error(y_test, y_pred))

0.4495753275045422


-----

Till now supervised learning is completed.

We dicussed 3 types :
1. decision tree
2. SVM
3. Naive bayes